# Generated by Django 2.1.4 on 2020-03-26 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TuWen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='images/', verbose_name='图片')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='文本')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '图文信息',
                'verbose_name_plural': '图文信息',
            },
        ),
    ]
